### ISSUE TITLE
Resource Prefix Name Error

### ISSUE THREAD

**Issue by mansoorsyed11** [feathr-ai/feathr#1010]
Hey Team @xiaoyongzhu , I have resources already Deployed so I didn't use ARM to deploy my azure resource after running your config path it's adding Redis along with my prefix name for instance {myredisname}redis.redis.cache.windows.net I don't know it can interpret my resource to configure why it's adding by default like below.

if FEATHR_CONFIG_PATH:
    config_path = FEATHR_CONFIG_PATH
else:
    config_path = generate_config(
        resource_prefix=RESOURCE_PREFIX,
        project_name=PROJECT_NAME,
        spark_config__spark_cluster=SPARK_CLUSTER,
        spark_config__azure_synapse__dev_url=AZURE_SYNAPSE_URL,
        spark_config__azure_synapse__pool_name=AZURE_SYNAPSE_SPARK_POOL,
        spark_config__databricks__workspace_instance_url=SPARK_CONFIG__DATABRICKS__WORKSPACE_INSTANCE_URL,
        databricks_cluster_id=DATABRICKS_CLUSTER_ID,
    )

with open(config_path, 'r') as f: 
    print(f.read())

api_version: 1
feature_registry:
  api_endpoint: https://Nonewebapp.azurewebsites.net/api/v1
offline_store:
  adls:
    adls_enabled: 'true'
  wasb:
    wasb_enabled: 'true'
online_store:
  redis:
    host: **Noneredis.redis.cache.windows.net**
    port: '6380'
    ssl_enabled: 'true'
project_config:
  project_name: nyc_taxi-
spark_config:
  databricks:
    config_template: '{"run_name": "FEATHR_FILL_IN", "libraries": [{"jar": "FEATHR_FILL_IN"}],
      "spark_jar_task": {"main_class_name": "FEATHR_FILL_IN", "parameters": ["FEATHR_FILL_IN"]},
      "existing_cluster_id": "0117-140050-k0mj89se"}'
    work_dir: dbfs:/nyc_taxi-
    workspace_instance_url: https://adb-5237615372246210.10.azuredatabricks.net
  spark_cluster: databricks
  spark_result_output_parts: '1'

**Comment by xiaoyongzhu** [comment]
I see, I think it's a bit hard coded.@loomlike can you help to decouple Redis from the configs?

**Comment by mansoorsyed11** [comment]
@xiaoyongzhu  its not only adds redis if you look above web app configs adding webapp as hardcoded.

**Comment by MansoorSyed1311** [comment]
I have solved this problem by providing config path

**Comment by mansoorsyed11** [comment]
I have solved this problem by providing config path
