### ISSUE TITLE
UI sandbox docker error issue 

### ISSUE THREAD

**Issue by mansoorsyed11** [feathr-ai/feathr#1076]
Hey team @xiaoyongzhu, im trying to deploy your ui sandbox in inside the terminal of aml work space im getting below error.

Platform : Azure Machine Learning Work Space 
Virtual machine size: Standard_DS12_v2 (4 cores, 28 GB RAM, 56 GB disk)
Processing unit: [CPU - Memory optimized](https://docs.microsoft.com/azure/virtual-machines/sizes-general)

# error 
 docker run -it --rm -p 8888:8888  -p 8000:8000 -p 80:80 -p 8080:8080 -p 7080:7080 --env API_BASE="api/v1" --env FEATHR_SANDBOX=True -e GRANT_SUDO=yes feathrfeaturestore/feathr-sandbox
docker: Error response from daemon: driver failed programming external connectivity on endpoint elegant_mendel (77d50ddb85424160610aa85e41975268a861d9e1713d5668544940d8d3f8bc68): Error starting userland proxy: listen tcp4 0.0.0.0:8888: bind: address already in use. 

# Note:
i have changed different ports same error I'm getting can you please help where exactly we are doing wrong.  or your sandbox can support azure cloud local environment with aml compute.

**Comment by windoze** [comment]
It looks like port 8888 is already used by some other program so docker cannot use it.
Could you please check if there is any other program using this port, or change port 8888 to some other number? e.g. `docker run ... -p 8889:8888 ...`.
