### ISSUE TITLE
[BUG] sql-registry api return error "value is not a valid dict"

### ISSUE THREAD

**Issue by XiaoZhiming** [feathr-ai/feathr#1111]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### Feathr version

v1.0.0

### System information

- **ANY**

### Describe the problem

when access sql-registry api  **/projects/{project}/datasources/{datasource}**
will return error **value is not a valid dict**

### Code to reproduce bug

http://127.0.0.1:8000/api/v1/projects/product_recommendation/datasources/{you datasource id}?project=product_recommendation&datasource={you datasource id}

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [X] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by enya-yx** [comment]
@XiaoZhiming, could you be more specific about steps to reproduce this problem? Did you get this error from UI or python client? We can help check if it's a bug or something else wrong, like the definition of feature or datasource.

**Comment by XiaoZhiming** [comment]
@enya-yx Sorry for reply late, I got the error " value is not a valid dict" from the web ui，the reason is  this func "@router.get("/projects/{project}/datasources/{datasource}")" in registry/sql-registry/main.py shoud return a dict , but the return value doesnot convert to dict explicitly

**Comment by enya-yx** [comment]
@XiaoZhiming I tried check data sources by web ui and it works well. Could you provide some details (eg. screenshot) about how did you create that feature and how to reproduce this error from ui?

**Comment by XiaoZhiming** [comment]
Hi @enya-yx  Thank you for your patience, Maybe my python version or some other env settings cause this error, when I change the return code to " s.to_dict()"
, the problem fixed in my env，the datasource I generated by  docs\samples\local_quickstart_notebook.ipynb  and my python version is 3.8.8.

and all other fun in main.py convert return type to dict explicitly
for example:

@router.get("/projects/{project}/datasources")
def get_project_datasources(project: str) -> List:
    p = registry.get_entity(project)
    source_ids = [s.id for s in p.attributes.sources]
    sources = registry.get_entities(source_ids)
    return list([e.to_dict() for e in sources])

@router.get("/features/{feature}")
def get_feature(feature: str) -> Dict:
    e = registry.get_entity(feature)
    if e.entity_type not in [EntityType.DerivedFeature, EntityType.AnchorFeature]:
        raise HTTPException(
            status_code=404, detail=f"Feature {feature} not found")
    return e.to_dict()

@router.get("/features/{feature}/lineage")
def get_feature_lineage(feature: str) -> Dict:
    lineage = registry.get_lineage(feature)
    return lineage.to_dict()

for the same reason, I think  "@router.get("/projects/{project}/datasources/{datasource}")"  's return value maybe  should  convert to dict explicitly  : )

**Comment by enya-yx** [comment]
@XiaoZhiming, got your point. Please help modify it then.
