### ISSUE TITLE
[BUG] Experimental Feature of ChatGPT is not available in local docker setup

### ISSUE THREAD

**Issue by ahlag** [feathr-ai/feathr#1137]
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### Feathr version

1.0.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:
Docker

### Describe the problem

@blrchen 
After tested the ChatGPT experimental features, I found out that the `feathr.chat` was not able to be run.
![screen_shot 2023-04-05 at 23 18 35](https://user-images.githubusercontent.com/51813538/230109381-2885b105-42da-4a64-b132-6f458d9c9324.png)

### What component(s) does this bug affect?

- [X] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by ahlag** [comment]
Tested installation with the following command. Feathr version is still `1.0`.
```sh
pip install git+https://github.com/feathr-ai/feathr.git#subdirectory=feathr_project
```

Related PR: https://github.com/feathr-ai/feathr/pull/1132/files

**Comment by blrchen** [comment]
@ahlag PR 1132 is not  included in version  `v1.0.0`. Could you please try to use latest feathr package from git repo instead of using `v1.0.0` in your notebook

**Comment by ahlag** [comment]
@blrchen 
Is there a doc on how to compile or run feathr locally from the repo?

**Comment by blrchen** [comment]
Running `pip install git+https://github.com/feathr-ai/feathr.git#subdirectory=feathr_project` should install latest feathr package with main branch code. This will ensure you get the code of PR 1132 which is required for the notebook.

**Comment by ahlag** [comment]
This solved the installation problem. ChatGPT feature tested.
https://github.com/feathr-ai/feathr/blob/a1da6596928e1d8acbb74f88c4f603f2508a258a/docs/dev_guide/python_dev_guide.md#installation
