### ISSUE TITLE
Feathr Client Experience Consistency with Feathr API Service

### ISSUE THREAD

**Issue by Yuqing-cat** [feathr-ai/feathr#410]
**Background**
- In previous version, we only have a thin Feathr client layer. 
- Now, a user hosted Registry API service along with access control plugin will be available soon. 
- How to align the user experience when user have / not have an API service. 

Take access control for example, if user already set up an access control plugin. And want to have the same experience in Feathr Client. It is not possible right now. 
Currently, users can have access control experience by stick to the UI or directly call the APIs. 

**Target**
1. Pure Feathr Client user experience is not influenced.
2. When API service enabled, the user experience in client & API calls & UI should be aligned as much as possible. 

**Proposal**
1. Enable a global setting to indicate if a Feathr Workspace enables API service or not. It needs to include all necessary information to set up API service
```json
{
    "registryAPI": {
        "enabled": "true",
        "type": "purview",
        "accessControl": "true",
        "endpoint":"",
    }
}
```
2. Based on the global setting, switch the backend logic: a. pure client `test mode`; b. API service. 
3. Enable token generation in Feathr Client for access control enabled API calls
4. Make sure the Standard behavior based on API Spec

**Comment by blrchen** [comment]
This is already completed as part of RBAC work, closing.
