### ISSUE TITLE
UI: not able to fully log out

### ISSUE THREAD

**Issue by blrchen** [feathr-ai/feathr#470]
Repro steps
1. Login Feathr UI
2. Click logout button
3. Wait till logout complete, if prompted for confirming which account to logout, selected current logged in one.
4. Fresh page

Expected
Login page should show up

Actual
Automatically logged in, which indicates previous logout does not take effect correctly.

**Comment by Yuqing-cat** [comment]
Issue status track: known issue, low priority.

**Comment by blrchen** [comment]
No longer able to repro. Closing
