### ISSUE TITLE
UI: Add detail page for data source

### ISSUE THREAD

**Issue by blrchen** [feathr-ai/feathr#489]
The ask is support detail page of data source. 

The experience is similar to feature detail pages: in data source list page, there is a details link for each row. Once the link is clicked, user will be redirected to detail page of data source. DataSource metadata and a list of features extracted from data source should be displayed here.

**Comment by ahlag** [comment]
@blrchen 
Please assign me

**Comment by blrchen** [comment]
Closing as completed in PR #620
