### ISSUE TITLE
Add convenient API to get multiple type of keys from Redis

### ISSUE THREAD

**Issue by xiaoyongzhu** [feathr-ai/feathr#536]
Currently Feathr only supports getting a single type of keys thru `client.get_online_features` or `client.multi_get_online_features`. Essentially they are just sending the HMGET commands to Redis, say for "product_id".

Per this discussion (https://feathrai.slack.com/archives/C036HEUQM08/p1658237223861509), it would be good to add a convenient API to get multiple type of keys, say get some "product_id" and get some "user_id" at once.

**Comment by ahlag** [comment]
@xiaoyongzhu 
Can I give this a try?

**Comment by blrchen** [comment]
Closing as this is completed by PR #919
