### ISSUE TITLE
[Bug] Failed to call registry API, status is 500, error is Internal Server Error

### ISSUE THREAD

**Issue by marrobi** [feathr-ai/feathr#653]
### Willingness to contribute

Yes. I would be willing to contribute to this for with guidance from the Feathr community.

### Description of proposal (what needs changing)

I am getting a `Failed to call registry API, status is 500, error is Internal Server Error` back from the Feather API web application when calling `client.list_registered_features(project_name="feathr_getting_started")`.

I am happy to troubleshoot this, but cannot get any debug logs. The web app log stream does not show any activity. How do I enable debug logs to be shown on the web app?

If you can explain how can look at making a docs contribution. 

Thank you.

**Comment by blrchen** [comment]
Hello @marrobi , thanks for raising this up. @windoze is working on improve the error returned by registry api to give more useful error message for trouble shot. In the meanwhile, you can follow these steps to check logs on server side

1. Go to azure portal, go to web app that hosts registry service
2. Navigate to `App Service Logs` blade and change `Application logging` to `File System`, click Save
3. Navigate to `Log Stream`, you will see the registry service log stream.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1607381/189971402-74af14f4-7a7c-46db-923b-0256676a116f.png">
<img width="1835" alt="image" src="https://user-images.githubusercontent.com/1607381/189971541-cb40c3b1-c8fa-4ca2-8194-a888b6e7b7f7.png">

**Comment by blrchen** [comment]
@marrobi @DJSaunders1997 , please try 0.9.0 release which should address this issue.  Thanks for your patience
