### ISSUE TITLE
[BUG] RBAC grant does not work if user email contains upper case characters

### ISSUE THREAD

**Issue by blrchen** [feathr-ai/feathr#677]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

v0.7.2

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:

### Describe the problem

To repro this issue
1. Grant admin to an user account that has upper case characters in email 

Expected Result
After grant is done, user should be able to access everything

Actual Result
After grant is done, user gets 403 error when access feature pages.

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [X] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by Yuqing-cat** [comment]
Fixed in #673
