### ISSUE TITLE
[BUG] Derived feature error

### ISSUE THREAD

**Issue by loomlike** [feathr-ai/feathr#752]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

0.8.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**: Ubuntu 20
- **Python version**: Python 3.10
- **Spark version, if reporting runtime issue**:

### Describe the problem

After #731, I'm getting the following error:

`Caused by: com.linkedin.feathr.common.exception.FeathrException: [FEATHR_ERROR] getFeatures() does not apply to SQLFeatureDerivationFunction`

Please confirm @jaymo001 

### What component(s) does this bug affect?

- [X] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by Yuqing-cat** [comment]
This error still exists. 
Repro step, call 
```python
client.get_offline_features(observation_settings=settings,
                            feature_query=feature_query,
                            output_path=output_path
                           )
```
with at least one derived feature in `feature_query`. 

Somehow it fails at `SQLFeatureDerivationFunction.scala` line 34, as below
```scala
  /**
   * WARNING: Dummy getFeatures method. This method shouldn't be called as SQLFeatureDerivationFunction is not computed here.
   */
  override def getFeatures(inputs: Seq[Option[common.FeatureValue]]): Seq[Option[common.FeatureValue]] = {
    throw new FeathrException(ErrorLabel.FEATHR_ERROR, "getFeatures() does not apply to SQLFeatureDerivationFunction")
  }
```

Per brief investigation, it's related with #731 which is a revert PR to #121. Both of the PRs have no description about the underneath logic. Cannot contribute to fix it either. 

@blrchen , I think we need to resolve this before next release.
