### ISSUE TITLE
[DOC] Local Spark E2E sample Notebook

### ISSUE THREAD

**Issue by Yuqing-cat** [feathr-ai/feathr#770]
### Willingness to contribute

Yes. I can contribute for this issue independently.

### Description of proposal (what needs changing)

At least 2 users have raised the needs of a local spark notebook. 
- "Hi there, do we have any notebook explaining local spark execution?"
- "I'm also Implementing feathr using local pyspark.  So I also need help regarding this."

**Comment by loomlike** [comment]
#756 this PR does include local spark run cells. You can either refer that notebook to create new one or simply add description to the README.md if necessary to explain about how to run feathr on local spark vs. Databricks. (I haven't tested that notebook on synapse).

**Comment by Uditanshu1612** [comment]
Hi @Yuqing-cat 
When are you going to upload the notebook or Py file to run the Feathr feature store in local Py-spark?

**Comment by Uditanshu1612** [comment]
Hi @Yuqing-cat 
I'm trying to Implement the Feathr in a Local Spark. But while fetching the feature from offline I'm facing an error of "FileNotFoundError: [WinError 2] The system cannot find the file specified"

![image](https://user-images.githubusercontent.com/115619000/198934629-abcbc395-4476-4719-89a2-523150bf76ea.png)

Can You Please tell me. How to resolve this error? Where I'm doing wrong.

**Comment by Yuqing-cat** [comment]
> Hi @Yuqing-cat I'm trying to Implement the Feathr in a Local Spark. But while fetching the feature from offline I'm facing an error of "FileNotFoundError: [WinError 2] The system cannot find the file specified"
> 
> ![image](https://user-images.githubusercontent.com/115619000/198934629-abcbc395-4476-4719-89a2-523150bf76ea.png)
> 
> Can You Please tell me. How to resolve this error? Where I'm doing wrong.

I think the path in Windows system should be using `\` rather than `/`. To deal with the file location, you may leverage os.path as well.

**Comment by Uditanshu1612** [comment]
Yes, I have tried with \. but as we know in jupyter notebook to give the path we use \\ (double back slash) but while giving \\ It gives an error of Parseerror.
![image](https://user-images.githubusercontent.com/115619000/198951677-b7378043-ca82-4fd1-8788-ad4b4fe21ba6.png)

![image](https://user-images.githubusercontent.com/115619000/198951729-c7f002fe-1172-4231-8517-19e6b1675b9b.png)

**Comment by Uditanshu1612** [comment]
And When I'm using / (Single front slash), It works fine because using the \ (Single Front Slash) it can access the config file. So same path I'm giving while fetching the feature offline But the I gives the error of FileNotFound

**Comment by Yuqing-cat** [comment]
> jupyter notebook to give the path we use \ (double back slash) but while giving \ It gives an error of Parseerror.

Please try relative path to bypass this like `output="output"`. I will try to repro this in win notebook when I have bandwidth.

**Comment by Uditanshu1612** [comment]
Yes, I tried with relative path too, but it still gives the error of FileNotFoundError.

**Comment by Yuqing-cat** [comment]
> Yes, I tried with relative path too, but it still gives the error of FileNotFoundError.

Please validate if the path you provided exist by `os.path.exists` and 
```python
if not os.path.exists(path):
            os.makedirs(path)
```

**Comment by Uditanshu1612** [comment]
Tes, I have checked the existence of path by os.path.exists(path). And It gives True that means the path is exists but still I'm facing the error of "FileNotFoundError: [WinError 2] The system cannot find the file specified"

![image](https://user-images.githubusercontent.com/115619000/198978573-9a6ec8ce-6474-4fe6-8e4b-4e7ade3e029b.png)

**Comment by ahlag** [comment]
@blrchen 
Can you assign me this issue? Thanks

**Comment by blrchen** [comment]
@ahlag thanks for picking this up, assigning!

**Comment by blrchen** [comment]
Closing this PR as a container based sandbox feature has been added, the sandbox comes with local spark, local redis, local jupyter server, local feathr registry in one docker image. For anyone who is interested to try sandbox, please check this doc https://feathr-ai.github.io/feathr/quickstart_local_sandbox.html
