### ISSUE TITLE
Feathr version: 0.10.4-rc1 not working getting Value Error in Client step but 0.9.0 worked previously 

### ISSUE THREAD

**Issue by mansoorsyed11** [feathr-ai/feathr#976]
hey team im getting a Value error after the new version release same code is working with 0.9.0 im trying to use 0.9.0 im getting installation error 
code : ! pip install "git+https://github.com/feathr-ai/feathr.git@0.9.0#subdirectory=feathr_project"
Python interpreter will be restarted.
Collecting git+https://github.com/feathr-ai/feathr.git@0.9.0#subdirectory=feathr_project
  Cloning https://github.com/feathr-ai/feathr.git (to revision 0.9.0) to /tmp/pip-req-build-xtmzuh6h
  Running command git clone -q https://github.com/feathr-ai/feathr.git /tmp/pip-req-build-xtmzuh6h
  WARNING: Did not find branch or tag '0.9.0', assuming revision or ref.
  Running command git checkout -q 0.9.0
  error: pathspec '0.9.0' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/feathr-ai/feathr.git@0.9.0#subdirectory=feathr_project. Command errored out with exit status 1: git checkout -q 0.9.0 Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q 0.9.0 Check the logs for full command output.
CalledProcessError: Command 'pip --disable-pip-version-check install git+https://github.com/feathr-ai/feathr.git@0.9.0#subdirectory=feathr_project' returned non-zero exit status 1.

#with Latest version :Feathr version: 0.10.4-rc1 

code: client = FeathrClient(
    config_path=config_path,
    credential=credential,
    use_env_vars=False,
)
Error is below: 

2023-01-17 13:29:53.037 | INFO     | feathr.utils._env_config_reader:get:65 - Config secrets__azure_key_vault__name is not found in the environment variable, configuration file, or the remote key value store.
2023-01-17 13:29:53.041 | INFO     | feathr.utils._env_config_reader:get:65 - Config offline_store__s3__s3_enabled is not found in the environment variable, configuration file, or the remote key value store.
2023-01-17 13:29:53.042 | INFO     | feathr.utils._env_config_reader:get:65 - Config offline_store__jdbc__jdbc_enabled is not found in the environment variable, configuration file, or the remote key value store.
2023-01-17 13:29:53.043 | INFO     | feathr.utils._env_config_reader:get:65 - Config offline_store__snowflake__snowflake_enabled is not found in the environment variable, configuration file, or the remote key value store.
2023-01-17 13:29:53.045 | INFO     | feathr.utils._env_config_reader:get:65 - Config spark_config__databricks__feathr_runtime_location is not found in the environment variable, configuration file, or the remote key value store.
ValueError: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<command-4053299415941067> in <cell line: 1>()
----> 1 client = FeathrClient(config_path=config_path)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a646cfc1-2561-408f-a74f-d28a802ad326/lib/python3.9/site-packages/feathr/client.py in __init__(self, config_path, local_workspace_dir, credential, project_registry_tag, use_env_vars)
    183                 )
    184 
--> 185         self._construct_redis_client()
    186 
    187         self.secret_names = []

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a646cfc1-2561-408f-a74f-d28a802ad326/lib/python3.9/site-packages/feathr/client.py in _construct_redis_client(self)
    482             port=port,
    483             password=password,
--> 484             ssl=self._str_to_bool(ssl_enabled))
    485         self.logger.info('Redis connection is successful and completed.')
    486         self.redis_client = redis_client

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a646cfc1-2561-408f-a74f-d28a802ad326/lib/python3.9/site-packages/feathr/client.py in _str_to_bool(self, s)
    468             return False
    469         else:
--> 470             raise ValueError # evil ValueError that doesn't tell you what the wrong value was
    471 
    472     def _construct_redis_client(self):

ValueError:

**Comment by xiaoyongzhu** [comment]
Thanks for reporting, we are fixing it

**Comment by blrchen** [comment]
@xiaoyongzhu please help take a look. I see _str_to_bool is added in the sandbox PR. @ahlag is experiencing same issue. @ahlag please watch this issue for fix status.

**Comment by xiaoyongzhu** [comment]
https://github.com/feathr-ai/feathr/pull/980

**Comment by ahlag** [comment]
@blrchen  (cc: @xiaoyongzhu )
Tested locally in my laptop. Everything went ok.

**Comment by xiaoyongzhu** [comment]
> @blrchen  (cc: @xiaoyongzhu )
> Tested locally in my laptop. Everything went ok.

Thanks!!

**Comment by mansoorsyed11** [comment]
Thanks @xiaoyongzhu for resolving this issue
